'use strict';

/**
 * Review controller — public submission + listing.
 *
 * Submission rules:
 *  - Held in 'pending' status by default (admin must approve).
 *  - If the product type has autoPublish enabled, status is set to 'approved'.
 *  - Reviews are stored in DB FIRST; no outbound calls until saved.
 *  - Photo/video uploads go to private S3 bucket (files not publicly accessible).
 *
 * JSON-LD for approved reviews is generated by the product controller.
 */

const Review      = require('../../models/Review');
const Product     = require('../../models/Product');
const ProductType = require('../../models/ProductType');
const { createError } = require('../../middlewares/errorHandler');

// ─── GET /api/reviews?productId=xxx — list approved reviews for a product ─────
const listReviews = async (req, res, next) => {
  try {
    const { productId, page = 1, limit = 10, sort = 'newest' } = req.query;
    if (!productId) return next(createError(400, 'productId is required.'));

    const pageNum  = Math.max(1, Number(page));
    const limitNum = Math.min(50, Number(limit));

    const sortMap = {
      newest:      { createdAt: -1 },
      oldest:      { createdAt: 1 },
      highest:     { rating: -1 },
      lowest:      { rating: 1 },
      helpful:     { helpfulCount: -1 },
    };
    const sortQuery = sortMap[sort] ?? sortMap.newest;

    const filter = { product: productId, status: 'approved' };

    const [reviews, total, ratingAgg] = await Promise.all([
      Review.find(filter)
        .sort(sortQuery)
        .skip((pageNum - 1) * limitNum)
        .limit(limitNum)
        .select('displayName rating title body media isVerifiedPurchase helpfulCount createdAt source')
        .lean(),

      Review.countDocuments(filter),

      Review.aggregate([
        { $match: filter },
        {
          $group: {
            _id: null,
            avgRating:   { $avg: '$rating' },
            count1:      { $sum: { $cond: [{ $eq: ['$rating', 1] }, 1, 0] } },
            count2:      { $sum: { $cond: [{ $eq: ['$rating', 2] }, 1, 0] } },
            count3:      { $sum: { $cond: [{ $eq: ['$rating', 3] }, 1, 0] } },
            count4:      { $sum: { $cond: [{ $eq: ['$rating', 4] }, 1, 0] } },
            count5:      { $sum: { $cond: [{ $eq: ['$rating', 5] }, 1, 0] } },
          },
        },
      ]),
    ]);

    const agg = ratingAgg[0] || {};
    const summary = {
      total,
      averageRating: agg.avgRating ? Math.round(agg.avgRating * 10) / 10 : null,
      distribution: {
        1: agg.count1 ?? 0,
        2: agg.count2 ?? 0,
        3: agg.count3 ?? 0,
        4: agg.count4 ?? 0,
        5: agg.count5 ?? 0,
      },
    };

    res.json({
      success: true,
      data: reviews,
      summary,
      pagination: { page: pageNum, limit: limitNum, total, pages: Math.ceil(total / limitNum) },
    });
  } catch (err) {
    next(err);
  }
};

// ─── POST /api/reviews — submit a new review ─────────────────────────────────
const submitReview = async (req, res, next) => {
  try {
    const {
      productId,
      rating,
      title,
      body,
      displayName,
      orderId,
    } = req.body;

    // Validate
    if (!productId) return next(createError(400, 'productId is required.'));
    if (!rating || rating < 1 || rating > 5) return next(createError(400, 'rating must be between 1 and 5.'));
    if (!body || body.trim().length < 10) return next(createError(400, 'Review body must be at least 10 characters.'));
    if (!displayName || !displayName.trim()) return next(createError(400, 'displayName is required.'));

    // Verify product exists
    const product = await Product.findById(productId)
      .select('_id productType')
      .lean();
    if (!product) return next(createError(404, 'Product not found.'));

    // Check if auto-publish is enabled for this product type
    let autoPublish = false;
    if (product.productType) {
      const pt = await ProductType.findById(product.productType)
        .select('reviewAutoPublish')
        .lean();
      autoPublish = pt?.reviewAutoPublish === true;
    }

    // Verify purchase flag
    let isVerifiedPurchase = false;
    let verifiedOrderId    = null;
    if (orderId && req.user) {
      const Order = require('../../models/Order');
      const order = await Order.findOne({
        _id: orderId,
        user: req.user._id,
        status: { $in: ['delivered', 'shipped', 'confirmed'] },
        'items.product': productId,
      }).lean();
      if (order) {
        isVerifiedPurchase = true;
        verifiedOrderId    = order._id;
      }
    }

    const review = await Review.create({
      product:            productId,
      user:               req.user?._id ?? null,
      displayName:        displayName.trim(),
      rating:             Number(rating),
      title:              title?.trim() ?? '',
      body:               body.trim(),
      isVerifiedPurchase,
      order:              verifiedOrderId,
      status:             autoPublish ? 'approved' : 'pending',
    });

    res.status(201).json({
      success: true,
      message: autoPublish
        ? 'Thank you! Your review has been published.'
        : 'Thank you! Your review has been submitted and is pending moderation.',
      data: {
        _id:        review._id,
        status:     review.status,
        rating:     review.rating,
        displayName: review.displayName,
      },
    });
  } catch (err) {
    next(err);
  }
};

// ─── POST /api/reviews/:id/helpful — mark a review as helpful ────────────────
const markHelpful = async (req, res, next) => {
  try {
    const review = await Review.findByIdAndUpdate(
      req.params.id,
      { $inc: { helpfulCount: 1 } },
      { new: true, select: 'helpfulCount' }
    ).lean();

    if (!review) return next(createError(404, 'Review not found.'));
    res.json({ success: true, helpfulCount: review.helpfulCount });
  } catch (err) {
    next(err);
  }
};

module.exports = { listReviews, submitReview, markHelpful };
